---
# tasks file for nextcloud

- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - ffmpeg
    state: present
    update-cache: true

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nextcloud_puid }}"
    group: "{{ nextcloud_pgid }}"
    mode: "{{ '0770' if item == nextcloud_data_volume else '0775' }}"
  with_items:
    - "{{ nextcloud_host_volume }}"
    - "{{ nextcloud_data_volume }}"
    - "{{ nextcloud_db_volume }}"

- name: Block - Docker compose tasks
  tags: update_docker_compose
  block:
    - name: Generate env file
      ansible.builtin.template:
        src: .env.j2
        dest: "{{ nextcloud_host_volume }}/.env"
        owner: "{{ nextcloud_puid }}"
        group: "{{ nextcloud_pgid }}"
        mode: '0644'

    - name: Generate docker compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ nextcloud_host_volume }}/docker-compose.yml"
        owner: "{{ nextcloud_puid }}"
        group: "{{ nextcloud_pgid }}"
        mode: '0644'

    - name: Run docker compose
      become: true
      community.docker.docker_compose_v2:
        project_src: "{{ nextcloud_host_volume }}"
        state: present
        remove_orphans: true
        build: never

- name: Wait until service is up
  ansible.builtin.uri:
    url: "http://localhost:{{ nextcloud_http_port }}/status.php"
    return_content: true
  register: nc_status
  retries: 10
  delay: 3
  until: nc_status.status == 200

- name: Check installation status
  community.docker.docker_container_exec:
    container: nextcloud
    user: abc
    command: php /app/www/public/occ status --output=json
  register: nc_status
  changed_when: false

- name: Setup admin user and database
  become: true
  vars:
    nc_installed: "{{ (nc_status.stdout | from_json).installed | default(false) }}"
  community.docker.docker_container_exec:
    container: nextcloud
    user: abc
    command: >
      php /app/www/public/occ maintenance:install
      --data-dir "/data"
      --database "{{ nextcloud_db_type }}"
      --database-host "database:{{ nextcloud_db_port }}"
      --database-name "{{ nextcloud_db_name }}"
      --database-user "{{ nextcloud_db_username }}"
      --database-pass "{{ nextcloud_db_password }}"
      --admin-user "admin"
      --admin-pass "{{ nextcloud_admin_password }}"
  when: not nc_installed

- name: Block - Thumbail generation tasks
  block:
    - name: Check preview status
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ config:system:get enable_previews
      register: nc_preview
      changed_when: false
      failed_when: false

    - name: Enable preview
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ config:system:set enable_previews --value=true
      when: not nc_preview.stdout

    - name: Get preview providers list
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ config:system:get enabledPreviewProviders --output=json
      register: nc_preview_providers
      changed_when: false
      failed_when: false

    - name: Add preview providers
      become: true
      vars:
        preview_providers_list: "{{ nc_preview_providers.stdout | default('[]') | regex_replace('^$', '[]') | from_json }}"
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ config:system:set enabledPreviewProviders {{ idx }} --value="{{ item }}"
      loop: "{{ nextcloud_preview_providers }}"
      loop_control:
        index_var: idx
        label: "{{ item }}"
      when:
        - item not in preview_providers_list

- name: Block - SMTP configuration taks
  tags: update_smtp
  block:
    - name: Check SMTP configuration
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ config:system:get mail_smtpmode
      register: nc_smtpmode
      failed_when: false
      changed_when: false

    - name: Disable SMTP server
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: >
          bash -c "
            php /app/www/public/occ config:system:delete mail_smtpmode &&
            php /app/www/public/occ config:system:delete mail_sendmailmode &&
            php /app/www/public/occ config:system:delete mail_smtphost &&
            php /app/www/public/occ config:system:delete mail_smtpport &&
            php /app/www/public/occ config:system:delete mail_smtpsecure &&
            php /app/www/public/occ config:system:delete mail_smtpauth &&
            php /app/www/public/occ config:system:delete mail_smtpname &&
            php /app/www/public/occ config:system:delete mail_smtppassword &&
            php /app/www/public/occ config:system:delete mail_from_address &&
            php /app/www/public/occ config:system:delete mail_domain
          "
      when:
        - not nextcloud_smtp_enabled
        - nc_smtpmode.stdout == 'smtp'

    - name: Enable SMTP server
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: >
          bash -c "
            php /app/www/public/occ config:system:set mail_smtpmode --value='smtp' &&
            php /app/www/public/occ config:system:set mail_sendmailmode --value='smtp' &&
            php /app/www/public/occ config:system:set mail_smtphost --value='{{ nextcloud_smtp_host }}' &&
            php /app/www/public/occ config:system:set mail_smtpport --value='{{ nextcloud_smtp_port }}' &&
            php /app/www/public/occ config:system:set mail_smtpsecure --value='{{ nextcloud_smtp_encryption }}' &&
            php /app/www/public/occ config:system:set mail_smtpauth --value='1' &&
            php /app/www/public/occ config:system:set mail_smtpname --value='{{ nextcloud_smtp_user }}' &&
            php /app/www/public/occ config:system:set mail_smtppassword --value='{{ nextcloud_smtp_password }}' &&
            php /app/www/public/occ config:system:set mail_from_address --value='no-reply' &&
            php /app/www/public/occ config:system:set mail_domain --value='{{ nextcloud_smtp_domain }}'
          "
      when:
        - nextcloud_smtp_enabled
        - nc_smtpmode.stdout != 'smtp'

- name: Block - Redis configuration tasks
  block:
    - name: Check Redis configuration
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ config:system:get redis host
      register: nc_redis_host
      changed_when: false
      failed_when: false

    - name: Configure Redis
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: >
          bash -c "
            php /app/www/public/occ config:system:set redis host --value='nextcloud-redis' &&
            php /app/www/public/occ config:system:set redis port --value='{{ nextcloud_redis_port }}' --type=integer &&
            php /app/www/public/occ config:system:set redis timeout --value='1.5' --type=double &&
            php /app/www/public/occ config:system:set redis password --value='' &&
            php /app/www/public/occ config:system:set memcache.local --value='\OC\Memcache\Redis' &&
            php /app/www/public/occ config:system:set memcache.locking --value='\OC\Memcache\Redis'
          "
      when: nc_redis_host.stdout != 'nextcloud-redis'
      changed_when: false

- name: Block - Trusted domains tasks
  tags: update_trusted_domains
  block:
    - name: Get current trusted domains
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ config:system:get trusted_domains --output=json
      register: nc_trusted_domains
      changed_when: false
      failed_when: false

    - name: Cleanup trusted domains list
      become: true
      vars:
        trusted_domains_list: "{{ nextcloud_trusted_domains_default + nextcloud_trusted_domains }}"
        trusted_domains_to_remove: >
          {{ (nc_trusted_domains.stdout | default('[]') | regex_replace('^$', '[]') | from_json)
            | difference(trusted_domains_list) }}
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ config:system:delete trusted_domains
      when: trusted_domains_to_remove | length > 0

    - name: Refresh trusted domains list
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ config:system:get trusted_domains --output=json
      register: nc_trusted_domains
      changed_when: false
      failed_when: false

    - name: Add trusted domains
      become: true
      vars:
        nc_trusted_domains_list: "{{ nc_trusted_domains.stdout | default('[]') | regex_replace('^$', '[]') | from_json }}"
        trusted_domains_list: "{{ nextcloud_trusted_domains_default + nextcloud_trusted_domains }}"
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: >
          php /app/www/public/occ config:system:set trusted_domains {{ idx }} --value='{{ item }}'
      loop: "{{ trusted_domains_list }}"
      loop_control:
        index_var: idx
        label: "{{ item }}"
      when:
        - item not in nc_trusted_domains_list

- name: Block - Application management tasks
  tags: update_apps
  block:
    - name: Get enabled apps
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ app:list --enabled --output=json
      register: nc_apps
      changed_when: false

    - name: Set applications facts
      ansible.builtin.set_fact:
        nc_apps_enabled: "{{ (nc_apps.stdout | from_json).enabled.keys() }}"
        nc_apps_list: "{{ nextcloud_applications | dict2items }}"

    - name: Enable applications
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: "php /app/www/public/occ app:enable {{ item.key }}"
      loop: "{{ nc_apps_list }}"
      loop_control:
        label: "{{ item.key }}"
      when:
        - item.value
        - item.key not in nc_apps_enabled

    - name: Disable applications
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: "php /app/www/public/occ app:disable {{ item.key }}"
      loop: "{{ nc_apps_list }}"
      loop_control:
        label: "{{ item.key }}"
      when:
        - not item.value
        - item.key in nc_apps_enabled

- name: Block - Users management task
  tags: update_users
  block:
    - name: Enable password policy
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ app:enable password_policy
      when: nextcloud_password_policy_enabled
      changed_when: false

    - name: Disable password policy
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ app:disable password_policy
      when: not nextcloud_password_policy_enabled
      changed_when: false

    - name: Get list of current users
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ user:list
      register: nc_users
      changed_when: false

    - name: Add users
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        env:
          OC_PASS: "{{ item.password }}"
        command: >
          bash -c "
            php /app/www/public/occ user:add --password-from-env --display-name='{{ item.display_name | default('') }}' {{ item.username }} &&
            php /app/www/public/occ user:setting {{ item.username }} settings email '{{ item.email | default('') }}'
          "
      loop: "{{ nextcloud_users }}"
      loop_control:
        label: "{{ item.username }}"
      when: item.username not in nc_users.stdout

    - name: Refresh user list
      become: true
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ user:list --output=json
      register: nc_users
      changed_when: false

    - name: Delete users
      become: true
      vars:
        users_to_keep: "{{ (nextcloud_users | map(attribute='username') | list) + ['admin'] }}"
        users_to_delete_json: >
          {{ nc_users.stdout | from_json | dict2items | map(attribute='key') | list | difference(users_to_keep) | to_json }}
        users_to_delete: "{{ users_to_delete_json | from_json }}"
      community.docker.docker_container_exec:
        container: nextcloud
        user: abc
        command: php /app/www/public/occ user:delete {{ item }}
      loop: "{{ users_to_delete }}"
      loop_control:
        label: "{{ item }}"
      when: users_to_delete | length > 0
